# TODO:
# * valgrind
# * CSA

language: c
os: linux
script: scripts/travis.sh $OPTS
jobs:
  include:
    - stage: baseline
      name: gcc
      compiler: gcc
    - name: clang
      compiler: clang
    - stage: checkers
      name: gcc-asan
      compiler: gcc-9
      env:
        - OPTS="ASAN=1"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
    - name: gcc-ubsan
      compiler: gcc-9
      env:
        - OPTS="UBSAN=1"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
    - stage: coverage
      name: gcc-coverage
      env:
        - COVERAGE=1
        - CODECOV_TOKEN="3a97a9de-16f9-4a37-80b4-9e853f0994f1"

addons:
  coverity_scan:
    project:
      name: "yugr/sortcheck"
      description: "Tool for detecting violations of ordering axioms in qsort/bsearch callbacks."
    notification_email: tetra2005@gmail.com
    build_command: make clean all
    branch_pattern: master
env:
  global:
   - secure: "nbJCdCpwmwFXX8++yL9jGOxrRT2OElq2PYl3qxKvv5d016xdM/RpA4W9fTGnZmcAemLa3n8kfXVkNVQNF30XGVJxfnnfxgArOKrDC4zBTIIYgnl2ePhZ3UQvJiLN9XXiOq/ExdIwSV1Xn4fF6vFP6R0xxRSEuQP0ATRnm/SUMLo4MHemDVs20ys2fmth63x6kTr7OMbEih98OvQWpZQofi8W7myH0GWK1disgA//pD6zUKuEeDOIrbwd+aidv0R3ncPQ30Lg+iyyPjyj0eBCNhsTbYHEDSZ6cyd8XbF8R5rFzjF9HmR0wYLNOZD7et8xMbdPJcjg67FiltwvJMK/fi83uvCw1AZ0Y+slNVuwON+YaE7OYdF86s7+K/7xy1LElkwQi4YePJvywnHCaAeRdeX6jtac4XsNEbR0atPKr25zM+gi+ClUpdoNMZue9hNMD7ExJbQK5Gd1V90P1dWq/Sx6aYFRc3hLOr2ssPlBXOfGLXBk3oZidJUf79bHSQJQ+NPlBnhppXaf3BKP+ahQJQ7UfiZfcO5A03JeG4+KeYUvAnJwYeJFVzP+jA7kvm8+5SL3hojdHIY9XYiUkfFCdq4t1mJA3hawDyu7Y+fxklaQZeHNvjZzgR5hyvEY+5xlyI5F9r+krSI5AxRKrRH34hf2x1onBRSriuDXjA7zNgg="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
