# TODO:
# * valgrind
# * CSA

language: c
os: linux
script: scripts/travis.sh $OPTS
jobs:
  include:
    - stage: baseline
      name: gcc
      compiler: gcc
    - name: clang
      compiler: clang
    - stage: checkers
      name: gcc-asan
      compiler: gcc-9
      env:
        - OPTS="ASAN=1"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
    - name: gcc-ubsan
      compiler: gcc-9
      env:
        - OPTS="UBSAN=1"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
    - stage: coverage
      name: gcc-coverage
      env:
        - COVERAGE=1
        - CODECOV_TOKEN="3a97a9de-16f9-4a37-80b4-9e853f0994f1"
