name: BSD
on:
  workflow_dispatch:
  schedule:
    # Run on Mondays
    - cron: '0 5 * * MON'
jobs:
  FreeBSD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        copyback: false
        prepare: pkg install -y gmake
        run: scripts/travis.sh
  NetBSD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        copyback: false
        prepare: /usr/sbin/pkg_add gmake
        run: scripts/travis.sh

